Feature
Godswilly/apple-clone pull request #1
Opened 2020-05-22 14:44 UTC by Godswilly

This is a clone application of archived apple website. In this project, my main aim was to learn how to align elements with float, flex, and grid in CSS. I tried doing it by creating an application that looks like the archived apple.com website.

2020-05-23 07:46 UTC, rammazzoti2000 requested changes
### Hello @Godswilly I am Alex your code reviewr for this project :raised_hands: 
God job this far, good use of HTML semantic, Readme file descriptive, Pull Request summary good enough, the commits should've been made more often with smaller chunks of code, for the next project remember small commits with meaningful description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_commits.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).
There are still some issues that are preventing me from approving this project, see the comments bellow :point_down: 
## :stop_sign: Required Changes :construction: :construction_worker: 
- [ ] There is a lot of repeating codes in our CSS file, let us apply the DRY rule. For more info kindly check this [article](https://speckyboy.com/good-bad-css-practices/) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
- [ ] The content should fill the entire page you have some space around left
![image](https://user-images.githubusercontent.com/3244654/82724519-fc6a9800-9cd6-11ea-9976-68617fcea0e4.png)
- [ ] The four images in the `end container` are overlapping and have a weird dark border due to the fact that you probably took screenshots of those pictures as a shortcut to bypass requirements, you can find the original pictures by download [this zip](https://archive.fo/download/UW4oR.zip) and extract it, you will find all the pictures needed inside the extracted folder.
- [ ] Here the footer has some alignment issues with the copyright text, should align along with the content above it, also the color of the a tags should be line in the original page
### Clone:
![image](https://user-images.githubusercontent.com/3244654/82724925-b8c55d80-9cd9-11ea-8ca3-8a3a598b4561.png)
### Original:
![image](https://user-images.githubusercontent.com/3244654/82724939-d2ff3b80-9cd9-11ea-8b8f-a638d030699d.png)
### <em>Kindly fix the REQUIRED issues and send another code review request.

Cheers and Happy coding! :clap: 

Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>
### :stop_sign: Status: Required Changes

2020-05-25 12:55 UTC, santiago-rodrig commented
# Pull Request under review by @santiago-rodrig (TSE)

2020-05-25 13:37 UTC, santiago-dev96 requested changes
# Changes required :no_entry_sign:

Your file `css/style.css` is full of bad practices, please implement the required changes and submit another CRR.

### OPTIONAL
- Make the search bar a bit more similar to the original page, it is taking too much width, and it is not being animated on focus; I suggest you to read [about CSS animations](https://developer.mozilla.org/en-US/docs/Web/CSS/animation)

You can find me in slack as **srodrig**, have a nice day! :wave:

2020-05-25 13:37 UTC, santiago-rodrig commented on css/style.css
> +}
This is useless, you are using a CSS reset file.
```suggestion
```

2020-05-25 13:37 UTC, santiago-rodrig commented on css/style.css
> +  flex-flow: column;
Better use this.
```suggestion
  flex-direction: column;
```

2020-05-25 13:37 UTC, santiago-rodrig commented on css/style.css
> +  background-color: #707070;
If you are going to use a linear gradient as background then this has no purpose.
```suggestion
```

2020-05-25 13:37 UTC, santiago-rodrig commented on css/style.css
> +  flex-flow: row;
```suggestion
  flex-direction: row;
```

2020-05-25 13:37 UTC, santiago-rodrig commented on css/style.css
> +  min-width: 103px;
```suggestion
 width: 103px;
```

2020-05-25 13:37 UTC, santiago-rodrig commented on css/style.css
> +  border: 2px solid transparent;
```suggestion
  padding: 2px;
```

2020-05-25 13:37 UTC, santiago-rodrig commented on css/style.css
> +  max-width: 100px;
```suggestion
  width: 100px;
```

2020-05-25 13:37 UTC, santiago-rodrig commented on css/style.css
> +  max-height: 15px;
```suggestion
  height: 15px;
```

2020-05-25 13:37 UTC, santiago-rodrig commented on css/style.css
> +  position: absolute;
```suggestion
```

2020-05-25 13:37 UTC, santiago-rodrig commented on css/style.css
> +}
```suggestion
```

2020-05-25 13:37 UTC, santiago-rodrig commented on css/style.css
> +  flex-flow: column;
```suggestion
  flex-direction: column;
```

2020-05-25 13:37 UTC, santiago-rodrig commented on css/style.css
> +  text-transform: none;
```suggestion
```

2020-05-25 13:37 UTC, santiago-rodrig commented on css/style.css
> +  flex-flow: row;
```suggestion
  flex-direction: row;
```

2020-05-25 13:37 UTC, santiago-rodrig commented on css/style.css
> +  position: relative;
```suggestion
```

2020-05-25 13:37 UTC, santiago-rodrig commented on css/style.css
> +  margin: auto;
```suggestion
```

2020-05-26 06:52 UTC, bolah2009 approved these changes
It's a 👍🏾 from me!

### :heavy_check_mark: Approved!

I would, however, recommend making the `div.end-content` element same width with the `div.page` element before merging. :relaxed: 

   ![record1](https://user-images.githubusercontent.com/36057474/82869177-b8210700-9f25-11ea-8849-234a391baedb.gif)

> ### Project specific
> The CSS background should `cover` the whole page irrespective of the screen size. This is a learning opportunity for you to use the background size and position properties.

_**Hint:** We can use [`background-size`](https://developer.mozilla.org/en/docs/Web/CSS/background-size) of `cover`, with a fitting `background-position`._

Good luck with your next projects. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2020-05-26 08:40 UTC, merged